# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/send"
  to = "http://13.211.126.119:5000/send"
  status = 200
  force = true

# Fix MIME type for JavaScript files
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

# Also handle .mjs files if you have any
[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"
    
# Handle TypeScript files that might be imported directly
[[headers]]
  for = "/*.ts"
  [headers.values]
    Content-Type = "text/javascript"
    
[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "text/javascript"